models:
  - name: chnl_layer_data
    description: "Integration layer for sales data, cleans and standardizes raw.sales"
  
  - name: chnl_department_data
    description: "Integration layer for sales data, cleans and standardizes raw.sales"
    columns:
      - name: employee_id 
        description: "Unique identifier for each employee"
        tests:
          - unique    
          - not_null  
      - name: hire_date 
        description: "hire date of each employee."
        tests:    
          - not_null 


          


