name: 'cority'
version: "1.0.0"
config-version: 2
profile: 'cority'

## Model Configuration
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

## Target Configuration
target-path: "target"
clean-targets: ["target", "dbt_packages"]

## Models Configuration - FIXED
models:
  +materialized: 'view'
  
  cority:
    
    intg:
      +schema: intg
      +tags: ["integration"]  # Fixed tag name
    
    chnl:
      +schema: chnl
      +tags: ["channel"]  # Fixed tag name
    
    pres:
      +schema: pres
      +tags: ["presentation"]  # Fixed tag name

## Seeds Configuration - FIXED
seeds:
  +enabled: true
  +quote_columns: true
  +schema: seeds

## Tests Configuration
tests:
  +severity: error
  +store_failures: true

## Variables
vars:
  project_name: cority
  is_prod: "{{ target.name == 'prod' }}"
  is_wip: "{{ target.name == 'wip' }}"

require-dbt-version: [">=1.0.0", "<2.0.0"]