name: 'cority'
version: "1.0.0"
config-version: 2
profile: 'cority'

## Model Configuration
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

## Target Configuration
target-path: "target"
clean-targets: ["target", "dbt_packages"]

## Models Configuration
models:
  cority:
    # Environment-specific materialization
    +materialized: "{{ 'view' if target.name == 'wip' else 'table' }}"
    
    # Each layer gets its own schema in the database
    # This will create: cority_wip.pres.table_name, cority_wip.chnl.table_name, etc.
    staging:
      +schema: staging
      +materialized: "{{ 'view' if target.name == 'wip' else 'table' }}"
      +tags: ["staging"]
    
    intg:
      +schema: intg
      +materialized: "{{ 'view' if target.name == 'wip' else 'table' }}"
      +tags: ["intg"]
    
    chnl:
      +schema: chnl
      +materialized: "{{ 'view' if target.name == 'wip' else 'table' }}"
      +tags: ["chnl"]
    
    pres:
      +schema: pres
      +materialized: "{{ 'view' if target.name == 'wip' else 'table' }}"
      +tags: ["pres"]

## Seeds Configuration
seeds:
  cority:
    +enabled: true
    +quote_columns: true
    +schema: seeds

## Tests Configuration
tests:
  +severity: warn
  +store_failures: "{{ true if target.name == 'wip' else false }}"

## Variables
vars:
  project_name: cority
  is_prod: "{{ target.name == 'prod' }}"
  is_wip: "{{ target.name == 'wip' }}"

require-dbt-version: [">=1.0.0", "<2.0.0"]

