cority:
  target: wip
  outputs:
    wip:
      type: snowflake
      account: 'SJBDBSY-BU63012'
      user: 'SUBODH'
      password: 'CorrectATG@123'
      role: 'ACCOUNTADMIN'
      database: CORITY_WIP  
      warehouse: COMPUTE_WH
      schema: WIP   
      threads: 4
      client_session_keep_alive: false
      query_tag: 'dbt_cority_wip'

