version: 2

sources:
  - name: raw
    schema: PUBLIC
    database: RAW
    tables:
      - name: DEMO_RAW_DATA
      - name: EMPLOYEES
        columns:
        - name: employee_id 
          description: "Unique identifier for each employee."
          tests:
           - unique    
           - not_null  
      - name: DEPARTMENTS
        columns:
        - name: DEPARTMENT_ID
          description: "Unique identifier for each employee."
          tests:
           - unique    
           - not_null  
models:
  - name: intg_raw_department
    description: 'department data'
    columns:
    - name: DEPARTMENT_ID
      tests:
      - unique    
      - not_null  
      
  - name: intg_subodh
    description: 'department data'
    columns:
    - name: DEPARTMENT_ID
      tests:
      - unique    
      - not_null  
    
