# name: dbt Advanced CI/CD

# on:
#   push:
#     branches: [ "**" ]
#   pull_request:
#     branches: [ "main" ]

# env:
#   DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}

# jobs:
#   branch-deployment:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: [3.9]
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
#       with:
#         fetch-depth: 0  # Important for dbt state comparison

#     - name: Setup Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: ${{ matrix.python-version }}

#     - name: Install dbt
#       run: pip install dbt-snowflake

#     - name: Get branch name
#       id: branch-name
#       uses: tj-actions/branch-names@v7

#     - name: Deploy to WIP (Feature Branches)
#       if: steps.branch-name.outputs.current_branch != 'main'
#       run: |
#         echo "Deploying to WIP environment for branch: ${{ steps.branch-name.outputs.current_branch }}"
#         dbt run --target wip
#         dbt test --target wip
#         dbt docs generate --target wip

#     - name: Deploy to PROD (Main Branch)
#       if: steps.branch-name.outputs.current_branch == 'main'
#       run: |
#         echo "Deploying to PROD environment"
#         dbt run --target prod
#         dbt test --target prod
#         dbt docs generate --target prod
#         dbt source freshness --target prod


name: dbt PROD Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DBT_SNOWFLAKE_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE || 'ACCOUNTADMIN' }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE || 'COMPUTE_WH' }}
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE_PROD || 'CORITY_PROD' }}
  SNOWFLAKE_THREADS: ${{ secrets.SNOWFLAKE_THREADS_PROD || '8' }}

jobs:
  prod-deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dbt
      run: pip install dbt-snowflake

    - name: Deploy to PROD
      env:
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA_PROD || 'PROD' }}
      run: |
        echo "Deploying to PROD environment"
        echo "Using PROD database: $SNOWFLAKE_DATABASE"
        echo "Using PROD schema: $SNOWFLAKE_SCHEMA"
        dbt run
        dbt test
        dbt docs generate
        dbt source freshness